### ISSUE TITLE
Proxy Error 

### ISSUE THREAD

**Issue by javixav** [sozialhelden/accessibility-cloud#68]
Hi AC team,

We're working at I Wheel Share on integrating accessibility data in our chatbot. We have recently noticed a proxy error (below) when we query the data. We think that when we query latitude like 48.868615, it might be too long. 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>502 Proxy Error</title>
    </head>
    <body>
        <h1>Proxy Error</h1>
        <p>The proxy server received an invalid
response from an upstream server.
            <br />
The proxy server could not handle the request
            <em>
                <a href="/search/places/around">GET&nbsp;/search/places/around</a>
            </em>.
            <p>
Reason: 
                <strong>Error reading from remote server</strong>
            </p>
        </p>
    </body>
</html>

**Comment by PanierAvide** [comment]
To give more details about this issue, this concerns mainly the cached server (fastly.net), which randomly takes forever or gives no response to our services.

**Comment by mutaphysis** [comment]
This might well be possible, @opyh  recently added caching for radius request. There is some url rewriting happening on fastly to allow rounding. This might cause the problem.

Can you try with shorter query params for the time being, until we deploy a fix?

**Comment by mutaphysis** [comment]
Can you give the exact url that causes this problem? Could this be a problem on your side, at least a proxy error indicates this.

`curl https://accessibility-cloud.freetls.fastly.net/place-infos.json\?latitude\=52.12122112312324\&longitude\=13.121232312413\&accuracy\=500\&appToken\=<APP-TOKEN>` works fine for me. I also do not see any redirects.

**Comment by PanierAvide** [comment]
Well, for now it seems to work fine, thanks for fixing this. The request causing issues was this one (auth token was in request headers) : `https://accessibility-cloud.freetls.fastly.net/place-infos?accuracy=20000&filter=at-least-partially-accessible-by-wheelchair&includeCategories=job_success&latitude=48.885&limit=100&longitude=2.361`

**Comment by PanierAvide** [comment]
We have again the issue, with this request : `https://accessibility-cloud.freetls.fastly.net/place-infos?accuracy=3000&filter=at-least-partially-accessible-by-wheelchair&latitude=48.868&longitude=2.353`

The server responds with error 503 and this output:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-cdg20728-CDG 1549980623 1841550683</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by opyh** [comment]
We had to make a change to data indexing recently, which seems to have slowed down queries with accuracy > 1000m. I'm going to fix this until next week.

When we implemented radius queries in the beginning, we did not mean them to be used for big result sets – rather for the 'what's directly around me?' use case, because they are difficult to cache efficiently. We have implemented a caching strategy for them, but it can't cover all cases in principle – and doesn't help if somebody is the first one to request something that creates a slow DB query ;)

Is there a way how we can reduce the number of results so the query still makes sense for your specific use case? Do you need this many results from accessibility.cloud for your use case or could they be further pre-filtered? How does the chatbot use the results of queries with big radiuses? We can easily add more specific data filters than `at-least-partially-accessible-by-wheelchair` if that helps you. If we know which filters you need, this could make the query more efficient directly on accessibility.cloud :) This probably makes more sense than requesting thousands of places from the server just to filter out most of it directly afterwards.

In the meantime, there are some workarounds:
- reduce the radius
- split the query into multiple xyz coordinate queries
(https://github.com/sozialhelden/accessibility-cloud/blob/788171b56cb2041e13977a3fa01b4081ca9afc86/both/api/shared/tile-indexing/getTilesEnclosingCircle.ts#L43 has code for converting a circle to coordinates of multiple tiles)

Hope that helps for now – sorry for the inconvenience!

**Comment by PanierAvide** [comment]
Thanks for this detailed answer. We are using large radiuses mainly in these cases :
- Object we're looking for are not so common (sports centres, job centres...)
- We are doing some specific filtering after getting response (like getting all places having toilets + public toilets, which can't be done for now directly on AC ? Or filtering data on custom attributes.

While the first case might not be an issue (if there are not many objects, the DB might be able to handle it). The problematic case is the second, where we retrieve a lot of data just to filter it on our side. We might need advanced filtering possibilities in order to ask the DB what's necessary in our case, and not get plenty of objects which will be unused.

**Comment by mutaphysis** [comment]
We just added the second use-case (accessible toilets) to the wheelmap app - and faced the same problem - client side filtering is a pita. Maybe we can add more advanced filters to accessibility-cloud in on of the next sprints. 

Indexing will always be a problem, so could you list all of your client side filtering logic, just for completeness sake?

**Comment by PanierAvide** [comment]
I will try to be as exhaustive as possible, we have filters on :
- Datasource (use only this dataset)
- Disability (wheelchair of course, but also any kind of disability)
- Place category (toilets being an edge case)
- Custom data we use in our datasets (and we would like to filter on tags being associated to features of Wheelmap dataset)
- Location (coordinates + radius)

**Comment by gchapototiws** [comment]
Hi AC Team, we have again the issue. Most of our requests get a error 502 Proxy Error. Has there been a change in radius policy or something else ? Thanks

**Comment by javixav** [comment]
Hi AC Team, we reduce all our radius to 10 km, but we still get the 502 Proxy Error. And more troubling is that it seems to follow a saw-toothed pattern alternating queries working and queries not working. In one day we can get 5 success and 5 failure. We hope you'll find the issue, thanks for your help !

**Comment by opyh** [comment]
Whoops, this totally went under my radar. Even if this was long ago: If this is still relevant, and if your queries are >1km wide, please use the x/y/z-based approach mentioned above. This should sustainably fix the issue.

Filtering - currently possible:

- source-based (`includeSourceIds=A,B,C,…`)
- location-based:
  - by center/radius for queries > 1km wide
  - as tiles by x/y/z coordinate for use cases covering larger geographic areas (if you need center/radius, [here's code to convert coordinates](https://github.com/sozialhelden/accessibility-cloud/issues/68#issuecomment-462986910))
- custom queries, e.g. by specific geographic boundaries as polygon. This feature exists, but can have side effects so we only do this in exceptional cases.

Not possible:

- We don't do filtering by disability, and discourage the use of accessibility criteria that claim that a place has offers for a target group with a disability ([explanation](https://sozialhelden.github.io/a11yjson/#physical-quantities-rating-scales-and-personal-profiles))
- filtering by accessibility criteria
- filtering by category - if you need this, you can split your data sources by category for now and filter by source ID

For this, you have to filter on the client side. It's a good idea to have your own cache in this case so you don't download big chunks of data for simple queries.

While I'd love to have more advanced filtering, it's currently not on our roadmap.
